var GAME_LEVELS = [
  ["                                                   vv                           ",
   "                                                                                ",
   "      @     o                                                                   ",
   "  xxxxxxxxxxxxxxxx       xxxxxxxxxxxx                                           ",
   "                 x                  xx                                          ",
   "                 x                   xxooo    ooo     oo    ooo     o           ",
   "                 xxxx                  xxx    xxxxx   xxxxxxxxxxxxxxxx          ",
   "       w            xxxxx                x!!!x   x!!!x                          ",
   "                        xxxxx            xxxxx   xx!xx                          ",
   "          xxx               xxx                    v                            ",
   "                x            xxxxxx                                             ",
   "                                                                                ",
   "                   x   x                                            o           ",
   "                           xxxxxxxxxxxxxxx   xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                         x   x                                  ",
   "                                         x   x                                  ",
   "                                         x   x                                  ",
   "                                         x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                         x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                         x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                         x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                         x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                         x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                         x!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "     w                                               o          oo                                                ",
   "    xxx  xxxxxxxx   xx  xxxx   xx   xxxxx          xxxx   xx   xxxx   xxx    xxx   xxxxxxxx   xxxx                ",
   "                                           xx                                                                     ",
   "                                             x                                                         xxx        ",
   "                                                                                                                  ",
   "                                                                                               xxxxxx             ",
   "                                                                                                                  ",
   "                                                                                     xxxxxxxx                     ",
   "                                                                                                                  ",
   "                                                                           xxx                                    ",
   "                                                                                                                  ",
   "                                                                  xxx                                             ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "      @                                               ooo                                               o         ",
   "xxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxx",
   "               x                                                                                                  ",
   "               x                                                                             xxxxx                ",
   "               x                                                                                                  ",
   "               x                                                                  ooo                   o         ",
   "               x                                                            xxxxxxxxxxxxxxx        xxxxxxxxxx     ",
   "               x                                           x   ooo =   x                                          ",
   "               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxx                                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                               xxxxxxxxxx       x             ",
   "                                                                                        x       x             ",
   "                                                                           xxxxx        x       x             ",
   "                                                                                        x=      x             ",
   "                                                                   xxxxxxxxx            xx=   xxx             ",
   "                                                              xxx                       x       x             ",
   "                                                        xxx                             x       x             ",
   "                                                  xxx                                   x   =   x             ",
   "                                            xxx                                         x       x             ",
   "     @                                                                                  x      =x             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               x       x             ",
   "                 x                           o                                          x     = x             ",
   "                 x                          xxx                                         x       x             ",
   "                 x                                               o                      x       x             ",
   "xxxxxxxxxxxxxxxxxx                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!   !!xxxxxxxxxxxxxx",
   "   | |           x                                                                      x       x             ",
   "                 x                                                  oooo                x   w   x             ",
   "                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  ooo    =x      x               v       v                                                                    ",
   "xxxxxxxxxxxx     x                                                        xxx                                 ",
   "     |  |  xx    x                                       ooo                                      ooo         ",
   "               xxx             o      o            xxxxxxxxxxxxxxxxxxxxxx      xxx      xxxxxxxxxxxxxxxxxxxxxx",
   "             xxx               xxx    xxx                                                                     ",
   "o                          xxx!!!!!!!!!!!!!!xxxxxxxx                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                 xx                           ",
   "                                                                                xxxx                          ",
   "             x       x  xxxxxxx  xxxxxxx  xxxxxxx  xxxxxxx  xxxxxxx  x     x    xxxx                          ",
   "              x     x      x     x           x     x     x  x     x   x   x      xx                           ",
   "               x   x       x     x           x     x     x  xxxxxxx    x x                                    ",
   "                x x        x     x           x     x     x  x    x      x        xx                           ",
   "                 x      xxxxxxx  xxxxxxx     x     xxxxxxx  x     x     x        xx                           ",
   "                                                                                                              ",
   "   @                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                                                              x               ",
   "                                                        xx     xx                             x               ",
   "                                                                                              x               ",
   "                             vxxx xxx xxx xxx xxx xxx   xx     xx                             x               ",
   "                              x   x   x   x x x    x    xx     xx                             x               ",
   "                             vxxx xxx x   xxx xxx  x       x x                                x               ",
   "                                x x   x   xx  x    x      x   x                               x               ",
   "                             vxxx xxx xxx x x xxx  x     xxxxxxx                              x               ",
   "                                                                                              x               ",
   "                             v                                                                x               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
